<a href="https://colab.research.google.com/github/Armanhsr0001/image-processing-lab-2301010037-/blob/main/Experiment_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import cv2
import numpy as np


In [ ]:
img=cv2.imread('/content/WhatsApp Image 2026-03-23 at 9.13.53 AM.jpeg',0)


In [ ]:
gauss=img + np.random.normal(0,20,img.shape)

In [ ]:
gauss=np.clip(gauss,0,255).astype(np.uint8)


In [ ]:
print(gauss)

[[  7  26  57 ...   6   0   4]
 [ 53  65   0 ...  20   0  57]
 [ 23  36  48 ...  24   4  19]
 ...
 [255 255 255 ...   0  31   0]
 [255 242 255 ...  30  21  14]
 [255 250 248 ...   0   0  31]]


In [ ]:
sp=img.copy()

In [ ]:
prob=0.2
rand=np.random.rand(*img.shape)
sp[rand<prob]=0

In [ ]:
sp[rand>1-prob]=255

In [ ]:
print(rand)

[[0.84749282 0.06730745 0.69686537 ... 0.43098803 0.4896859  0.19901155]
 [0.34845042 0.92746053 0.63403722 ... 0.25587495 0.65174807 0.82768008]
 [0.61542889 0.63013214 0.6178164  ... 0.28820429 0.33060236 0.71010031]
 ...
 [0.11935179 0.8888571  0.25187266 ... 0.2107807  0.50210173 0.58964345]
 [0.75302007 0.67841778 0.99684754 ... 0.75356839 0.63133609 0.32169834]
 [0.45278928 0.98892635 0.96418144 ... 0.71782809 0.77105899 0.35534293]]


In [ ]:
cv2.imwrite('gauss.jpg',gauss)


True

In [ ]:
from google.colab import files
files.download("gauss.jpg")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
cv2.imwrite("sp.jpg",sp)

True

In [ ]:
files.download("sp.jpg")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
mean_filt = cv2.blur(gauss,(3,3))

In [ ]:
meadian_filt=cv2.medianBlur(sp,3)

In [ ]:
cv2.imwrite("gauss.jpg",mean_filt)

True

In [ ]:
files.download("gauss2.jpg")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
cv2.imwrite("sp.jpg",meadian_filt)

True

In [ ]:
files.download("gauss3.jpg")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>